EV3RT CXX API Reference [English]: MotorTank Class Reference
MotorTank Class Reference
Class MotorTank. API for working with two motors together.
#include <ev3cxx_motor_tank.h>
Public Member Functions
MotorTank (MotorPort left_motor_port, MotorPort right_motor_port, MotorType type=MotorType::LARGE)
Constructor of class MotorTank.
void off (bool brake=true)
Stop motors.
void on (int left_speed=50, int right_speed=50)
Set speed on regulated motors.
void unregulated (int left_power=50, int right_power=50)
Set power on unregulated motors.
void onForDegrees (int left_speed=50, int right_speed=50, int degrees=360, bool_t brake=true, bool_t blocking=true, unsigned int wait_after_ms=60)
Set number of degrees to rotate with regulated motors.
void onForRotations (int left_speed=50, int right_speed=50, float rotations=1, bool_t brake=true, bool_t blocking=true, unsigned int wait_after_ms=60)
Set number of rotations to rotate with regulated motors.
void onForSeconds (int left_speed=50, int right_speed=50, unsigned int time_ms=1000, bool_t brake=true)
Rotates the motor for a given time.
void resetPosition ()
Reset the angular position of the motors to zero.
Motor & leftMotor ()
Return reference to the left motor.
const Motor & leftMotor () const
Return const reference to the left motor.
Motor & rightMotor ()
Return reference to the right motor.
const Motor & rightMotor () const
Return const reference to the right motor.
Private Attributes
Motor m_left_motor
Motor m_right_motor
Additional Inherited Members
Static Public Attributes inherited from MotorConstants
static const int POWER_MAX = 100
Max power on motor.
static const int POWER_MIN = -100
Min power on motor.
static constexpr float NUMBER_OF_DEGREES_PER_ROTATION = 360.0
Detailed Description
Class MotorTank. API for working with two motors together.
Definition at line 17 of file ev3cxx_motor_tank.h.
Constructor & Destructor Documentation
MotorTank()
MotorTank (MotorPort left_motor_port, MotorPort right_motor_port, MotorType type = MotorType::LARGE) inline
Constructor of class MotorTank.
Parameters
left_motor_port Port number
right_motor_port Port number
type Type of motor ports: motor_type_t
Definition at line 31 of file ev3cxx_motor_tank.h.
     : m_left_motor(left_motor_port, type),
       m_right_motor(right_motor_port, type)
     {}
Member Function Documentation
leftMotor() [1/2]
Motor& leftMotor () inline
Return reference to the left motor.
Returns
Return Motor&.
Definition at line 148 of file ev3cxx_motor_tank.h.
 { return m_left_motor; }
leftMotor() [2/2]
const Motor& leftMotor () const inline
Return const reference to the left motor.
Returns
Return const Motor&.
Definition at line 155 of file ev3cxx_motor_tank.h.
 { return m_left_motor; }
off()
void off (bool brake = true) inline
Stop motors.
Set the motors power or speed to 0 and depending on param brake will brake the motors.
Parameters
brake Start braking the motors (true = braking, false = not braking). Default value is true.
Definition at line 42 of file ev3cxx_motor_tank.h.
References Motor::off().
Referenced by MotorTank::onForSeconds().
{
         m_left_motor.off(brake);
         m_right_motor.off(brake);
     }
on()
void on (int left_speed = 50, int right_speed = 50) inline
Set speed on regulated motors.
Using regulated motors driver (motors should has constant speed) and param power is equivalent to speed. Motor controls real power to keep constant speed.
Parameters
left_speed Left motor speed. Range: -100 to +100. A negative value turns the wheel backwards. Default value is 50. If a out-of-range value is given, it will be clipped to the minimum (-100) or maximum (100) value.
right_speed Right motor speed. Range: -100 to +100. A negative value turns the wheel backwards. Default value is 50. If a out-of-range value is given, it will be clipped to the minimum (-100) or maximum (100) value.
Definition at line 57 of file ev3cxx_motor_tank.h.
References Motor::on().
Referenced by MotorTank::onForSeconds().
{
         m_left_motor.on(left_speed);
         m_right_motor.on(right_speed);
     }
onForDegrees()
void onForDegrees (int left_speed = 50, int right_speed = 50, int degrees = 360, bool_t brake = true, bool_t blocking = true, unsigned int wait_after_ms = 60) inline
Set number of degrees to rotate with regulated motors.
Parameters
left_speed Left motor speed. Range: -100 to +100. Default value is 50.
right_speed Right motor speed. Range: -100 to +100. Default value is 50.
degrees Number of degrees for rotation of the forward or faster motor. Default value is 360.
brake If true, then motor start braking after reach the position (= degrees).
blocking true (The function will be blocked until the move is finished), or false (The function will not be blocked). Default value is false.
wait_after_ms Adds wait after the function executes. Default wait is 60 ms. It is important because of some race condition when another motor rotation follows immediately
Definition at line 88 of file ev3cxx_motor_tank.h.
References Motor::onForDegrees().
Referenced by MotorTank::onForRotations().
{
         int labs = abs(left_speed);
         int rabs = abs(right_speed);
         if (labs > rabs) {
             const float sr = float(rabs) / float(labs);
             m_right_motor.onForDegrees(right_speed, degrees * sr, brake, false, 0);
             m_left_motor.onForDegrees (left_speed, degrees, brake, blocking, wait_after_ms);
         } else {
             const float sr = rabs != 0 ? float(labs) / float(rabs) : 0;
             m_left_motor.onForDegrees (left_speed, degrees * sr, brake, false, 0);
             m_right_motor.onForDegrees(right_speed, degrees, brake, blocking, wait_after_ms);
         }
     }
onForRotations()
void onForRotations (int left_speed = 50, int right_speed = 50, float rotations = 1, bool_t brake = true, bool_t blocking = true, unsigned int wait_after_ms = 60) inline
Set number of rotations to rotate with regulated motors.
Parameters
left_speed Left motor speed. Range: -100 to +100. Default value is 50.
right_speed Right motor speed. Range: -100 to +100. Default value is 50.
rotations Number of rotations for rotation of the forward or faster motor. Default value is 1.
brake If true, then motor start braking after reach the position (= degrees).
blocking true (The function will be blocked until the move is finished), or false (The function will not be blocked). Default value is false.
wait_after_ms Adds wait after the function executes. Default wait is 60 ms. It is important because of some race condition when another motor rotation follows immediately
Definition at line 114 of file ev3cxx_motor_tank.h.
References MotorTank::onForDegrees().
{
         onForDegrees(left_speed, right_speed, rotations * NUMBER_OF_DEGREES_PER_ROTATION, brake, blocking, wait_after_ms);
     }
onForSeconds()
void onForSeconds (int left_speed = 50, int right_speed = 50, unsigned int time_ms = 1000, bool_t brake = true) inline
Rotates the motor for a given time.
Parameters
left_speed Speed of left motor. Range: -100 to +100. Default value is 50.
right_speed Speed of right motor. Range: -100 to +100. Default value is 50.
ms Number of miliseconds for rotate with motor. Default value is 1000.
brake If true, then motor start braking after reach the position (= degrees).
Definition at line 126 of file ev3cxx_motor_tank.h.
References MotorTank::off(), and MotorTank::on().
{
         on(left_speed, right_speed);
         tslp_tsk(time_ms);
         off(brake);
     }
resetPosition()
void resetPosition () inline
Reset the angular position of the motors to zero.
Setting the value of the angular position sensor of the motor does not affect the actual power and position of the motor.
Definition at line 137 of file ev3cxx_motor_tank.h.
References Motor::resetPosition().
     {
         m_left_motor.resetPosition();
         m_right_motor.resetPosition();
     }
rightMotor() [1/2]
Motor& rightMotor () inline
Return reference to the right motor.
Returns
Return Motor&.
Definition at line 162 of file ev3cxx_motor_tank.h.
 { return m_right_motor; }
rightMotor() [2/2]
const Motor& rightMotor () const inline
Return const reference to the right motor.
Returns
Return const Motor&.
Definition at line 169 of file ev3cxx_motor_tank.h.
 { return m_right_motor; }
unregulated()
void unregulated (int left_power = 50, int right_power = 50) inline
Set power on unregulated motors.
Motors work with constant power, NOT speed. Speed changes depend on load.
Parameters
left_power Left motor power. Range: -100 to +100. A negative value turns the wheel backwards. Default value is 50. If a out-of-range value is given, it will be clipped to the minimum (-100) or maximum (100) value.
right_power Right motor power. Range: -100 to +100. A negative value turns the wheel backwards. Default value is 50. If a out-of-range value is given, it will be clipped to the minimum (-100) or maximum (100) value.
Definition at line 71 of file ev3cxx_motor_tank.h.
References Motor::unregulated().
{
         m_left_motor.unregulated(left_power);
         m_right_motor.unregulated(right_power);
     }