EV3RT CXX API Reference [English]: GyroSensor Class Reference
GyroSensor Class Reference
Class GyroSensor. API for working with gyro sensor.
#include <ev3cxx_gyro_sensor.h>
Public Member Functions
GyroSensor (SensorPort port)
Constructor of class GyroSensor.
int angle ()
Get angle in degrees from gyro.
int rate ()
Get angular speed from gyro. Speed = degrees per seconde.
void reset ()
Reset gyro.
void resetHard ()
Hard reset gyro. Solve the problem with drifting value after standard reset().
Additional Inherited Members
Protected Member Functions inherited from Sensor
Sensor (SensorPort port, sensor_type_t type)
Constructor of class Sensor.
virtual ~Sensor ()
Destructor of class Sensor.
sensor_port_t getPort ()
Get sensor port set in constructor.
sensor_type_t getType ()
Get actual sensor type.
Protected Attributes inherited from Sensor
sensor_port_t m_port
sensor_type_t m_type
Detailed Description
Class GyroSensor. API for working with gyro sensor.
Definition at line 20 of file ev3cxx_gyro_sensor.h.
Constructor & Destructor Documentation
GyroSensor()
GyroSensor (SensorPort port) inline
Constructor of class GyroSensor.
Parameters
port Port index (1-4).
Definition at line 28 of file ev3cxx_gyro_sensor.h.
References GyroSensor::resetHard().
                                 : Sensor(port, GYRO_SENSOR) {
         resetHard();
     }
Member Function Documentation
angle()
int angle () inline
Get angle in degrees from gyro.
Not recommended use angle() and rate() in same time => call rate() reset initial position in angle().
Returns
Number of degrees of robot rotation from initial position. Range: from -32768 to 32767 (after overflow, the value goes to the opposite range: +32767 +1 => -32768)
Definition at line 39 of file ev3cxx_gyro_sensor.h.
Referenced by GyroSensor::resetHard().
                 {
         return ev3_gyro_sensor_get_angle(m_port);
     }
rate()
int rate () inline
Get angular speed from gyro. Speed = degrees per seconde.
Not recommended use angle() and rate() in same time => call rate() reset initial position in angle().
Returns
Range: 0 - 100
Definition at line 49 of file ev3cxx_gyro_sensor.h.
Referenced by GyroSensor::resetHard().
                {
         return ev3_gyro_sensor_get_rate(m_port);
     }
reset()
void reset () inline
Reset gyro.
Set the zero value on gyro when the robot not move => affect the angle() and rate() values Doesn't work everytime: https://bricks.stackexchange.com/questions/7115/how-can-ev3-gyro-sensor-drift-be-handled Then you need resetHard().
Definition at line 60 of file ev3cxx_gyro_sensor.h.
Referenced by GyroSensor::resetHard().
                  {
         ev3_gyro_sensor_reset(m_port);
     }
resetHard()
void resetHard () inline
Hard reset gyro. Solve the problem with drifting value after standard reset().
Set firstly gyro to one mode (angle) => then reset() => second mode (rate) => reset() => first mode (angle)
Definition at line 69 of file ev3cxx_gyro_sensor.h.
References GyroSensor::angle(), GyroSensor::rate(), and GyroSensor::reset().
Referenced by GyroSensor::GyroSensor().
                      {
         angle();
         reset();
         rate();
         reset();
         angle();
     }