sudo: required
dist: trusty
language: cpp

compiler: gcc

before_install:
# -  sudo apt-get remove binutils-arm-none-eabi gcc-arm-none-eabi
 - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y # -qq is for travis CI
 - sudo apt-get update
 - sudo apt-get install gcc-arm-embedded u-boot-tools libboost1.55-all-dev -y

before_script:
 - ls -la
 - git clone https://github.com/RoboticsBrno/RB-ev3rt-hrp2/
 - cd RB-ev3rt-hrp2
 - git submodule init
 - git submodule update
 - cd ..
 - rm -rf RB-ev3rt-hrp2/sdk/*
 - cp -rv common/ RB-ev3rt-hrp2/sdk/common/
 - cp -rv workspace/ RB-ev3rt-hrp2/sdk/workspace/
 - cp Makefile.sdk.conf RB-ev3rt-hrp2/sdk/Makefile.sdk.conf
 - cd RB-ev3rt-hrp2
 - cd cfg
 - make
 - cd ../base-workspace
 - make app=loader
 - cd ../sdk/workspace

script: 
 - make app=helloev3
 - make app=ev3cxx-motor
 - make app=ev3cxx-display
 - make app=ev3cxx-file
 - ls -la
